# Generated by Django 4.2.7 on 2025-11-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='stutter_frequency',
            field=models.FloatField(default=0.0, help_text='Stutters per minute'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='stutter_timestamps',
            field=models.JSONField(default=list, help_text='List of (start, end) timestamp tuples for stutter events'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='total_stutter_duration',
            field=models.FloatField(default=0.0, help_text='Total duration of stuttering in seconds'),
        ),
    ]
